{% set name = "opsdroid" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82f40ec060a8bf286158ed82bb93557001be5b08861a6ad5e5c216c879723b15

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - opsdroid = opsdroid.__main__:main

requirements:
  host:
    - python >=3.5
    - babel
    - pip
  run:
    - python >=3.5
    - aiohttp
    - aioslacker
    - arrow
    - babel
    - click
    - nbconvert
    - nbformat
    - pycron
    - pyyaml
    - websockets
    - appdirs
    - multidict

test:
  imports:
    - opsdroid
    - opsdroid.parsers
    - opsdroid.database
    - opsdroid.connector
    - opsdroid.connector.slack
    - opsdroid.connector.websocket
  commands:
    - opsdroid --help


about:
  home: https://opsdroid.github.io/
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'An open source ChatOps bot framework.'

  description: |
    An open source chat bot framework written in python. It is designed to be extendable, scalable and simple.
  doc_url: https://opsdroid.readthedocs.io/
  dev_url: https://github.com/opsdroid/opsdroid

extra:
  recipe-maintainers:
    - FabioRosado
    - jacobtomlinson
    - synapticarbors
    - Cadair
